name: 'gh-export-godot-project'
branding:
  icon: 'external-link'  
  color: 'orange'
description: 'Runs godot export configuration'
inputs:
  project-directory:
    description: "Base directory relativ to the git root"
    required: true
    default: "./"  
  export-debug: 
    description: 'Export with "debug" symbols'
    required: false
    default: ""
  export-pack:
    description: "Export just the .pck/.zip file"
    required: false
    default: ""
  export-platform:
    description: "Export for platform (.pck + .exe)"
    required: false
    default: "y"
  platform:
    description: "Platform to export for (from export_presets.cfg)"
    required: true
    default: "Linux/X11"
  executable-name:
    description: "Name of executable (for windows append '.exe')"
    required: true
    default: "game"
  godot-version:
    description: "Version of godot to use (docker)"
    required: true
    default: '3.4'
  base-docker:
    description: "base docker container url"
    default: 'ghcr.io/kuhnchris/godot-github-ci-actions'

runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/action.sh
      shell: bash
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      env:
        GODOT_VERSION: ${{ inputs.godot-version }}
        ACTION_PATH: ${{ github.action_path }}
        PROJECT_DIRECTORY: ${{ inputs.project-directory }}
        EXPORT_DEBUG: ${{ inputs.export-debug }}
        EXPORT_PACK: ${{ inputs.export-pack }}
        EXPORT_PLATFORM: ${{ inputs.export-platform }}
        PLATFORM: ${{ inputs.platform }}
        EXECUTABLE_NAME: ${{ inputs.executable-name }}
        BASE_DOCKER: ${{inputs.base-docker}}
